# See https://pre-commit.com/ for usage and config
repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit, push]
    language: system
    entry: micromamba run -n sc_datavis isort
    types: [python]

  - id: black
    name: black
    stages: [commit, push]
    language: system
    entry: micromamba run -n sc_datavis black
    types: [python]

  - id: flake8
    name: flake8
    stages: [commit, push]
    language: system
    entry: micromamba run -n sc_datavis flake8
    types: [python]
