name: sc_datavis
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.12

  # for running
  - streamlit
  - pandas
  - plotly
  - seaborn
  - matplotlib

  # for pre-commit
  - black
  - flake8
  - isort
  - pre-commit
